{
//=========Macro generated from canvas: cBFraction2/b-jet Fraction
//=========  (Thu Jul 26 18:44:04 2012) by ROOT version5.26/00
   TCanvas *cBFraction2 = new TCanvas("cBFraction2", "b-jet Fraction",20,42,700,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   cBFraction2->Range(-21.42857,-0.008674699,121.4286,0.06361446);
   cBFraction2->SetFillColor(0);
   cBFraction2->SetBorderMode(0);
   cBFraction2->SetBorderSize(2);
   cBFraction2->SetTickx(1);
   cBFraction2->SetTicky(1);
   cBFraction2->SetLeftMargin(0.15);
   cBFraction2->SetRightMargin(0.15);
   cBFraction2->SetTopMargin(0.05);
   cBFraction2->SetBottomMargin(0.12);
   cBFraction2->SetFrameFillStyle(0);
   cBFraction2->SetFrameBorderMode(0);
   cBFraction2->SetFrameFillStyle(0);
   cBFraction2->SetFrameBorderMode(0);
   Double_t xAxis1[4] = {0, 20, 50, 100}; 
   
   TH1D *hBFractionMC2 = new TH1D("hBFractionMC2","hBFractionMC",3, xAxis1);
   hBFractionMC2->SetBinContent(1,0.02852294);
   hBFractionMC2->SetBinContent(2,0.0276771);
   hBFractionMC2->SetBinContent(3,0.02747248);
   hBFractionMC2->SetBinError(1,0.0007256208);
   hBFractionMC2->SetBinError(2,0.0006088277);
   hBFractionMC2->SetBinError(3,0.0006572631);
   hBFractionMC2->SetMinimum(0);
   hBFractionMC2->SetMaximum(0.06);
   hBFractionMC2->SetEntries(6);
   hBFractionMC2->SetLineColor(2);
   hBFractionMC2->SetLineStyle(0);
   hBFractionMC2->SetLineWidth(2);
   hBFractionMC2->SetMarkerColor(2);
   //hBFractionMC2->SetMarkerStyle(20);
   hBFractionMC2->SetMarkerStyle(1);
   hBFractionMC2->SetMarkerSize(0);
   hBFractionMC2->GetXaxis()->SetTitle("Centrality");
   hBFractionMC2->GetXaxis()->CenterTitle(true);
   hBFractionMC2->GetXaxis()->SetLabelFont(43);
   hBFractionMC2->GetXaxis()->SetLabelFont(43);
   hBFractionMC2->GetXaxis()->SetLabelSize(28);
   hBFractionMC2->GetXaxis()->SetLabelSize(28);
   //tex->SetTextFont(43);
   //tex->SetTextSize(23);

   hBFractionMC2->GetXaxis()->SetLabelOffset(0.007);
   //hBFractionMC2->GetXaxis()->SetLabelSize(0.05);
   // hBFractionMC2->GetXaxis()->SetTitleSize(0.05);
   hBFractionMC2->GetXaxis()->SetTitleFont(43);
   hBFractionMC2->GetXaxis()->SetTitleSize(28);
   hBFractionMC2->GetYaxis()->SetTitle("b-jet fraction");
   hBFractionMC2->GetYaxis()->CenterTitle(true);
   hBFractionMC2->GetYaxis()->SetNdivisions(408);
   hBFractionMC2->GetYaxis()->SetLabelFont(43);
   hBFractionMC2->GetYaxis()->SetLabelOffset(0.007);
   hBFractionMC2->GetYaxis()->SetLabelSize(28);
   hBFractionMC2->GetYaxis()->SetTitleSize(28);
   hBFractionMC2->GetYaxis()->SetTitleOffset(1.3);
   hBFractionMC2->GetYaxis()->SetTitleFont(43);
   hBFractionMC2->GetYaxis()->SetTitleFont(43);
   hBFractionMC2->GetYaxis()->SetTitleSize(28);

   hBFractionMC2->GetZaxis()->SetLabelFont(43);
   hBFractionMC2->GetZaxis()->SetLabelSize(28);
   hBFractionMC2->GetZaxis()->SetLabelOffset(0.007);
   hBFractionMC2->GetZaxis()->SetTitleFont(43);
   hBFractionMC2->GetZaxis()->SetTitleSize(28);

   hBFractionMC2->Draw("hist");
   TLatex *   tex = new TLatex(0.5,0.0612,"CMS Preliminary");
   tex->SetTextFont(43);
   tex->SetTextSize(23);
   tex->SetLineWidth(1);
   tex->Draw();
   tex = new TLatex(67.5,0.0612,"#sqrt{s_{NN}} = 2.76 TeV");
   tex->SetTextFont(43);
   tex->SetTextSize(23);
   tex->SetLineWidth(1);
   tex->Draw();
   tex = new TLatex(20,0.005,"80 < Jet p_{T} < 100 GeV/c");
   tex->SetTextFont(43);
   tex->SetLineWidth(1);
   tex->SetTextSize(23);
   tex->Draw();
   
   TGraphErrors *gre = new TGraphErrors(4);
   gre->SetName("gSyst");
   gre->SetTitle("Graph");
   gre->SetFillColor(5);
   gre->SetMarkerStyle(20);
   gre->SetPoint(0,10,0.0381308);
   gre->SetPointError(0,10,0.007319653);
   gre->SetPoint(1,35,0.02899246);
   gre->SetPointError(1,15,0.007408438);
   gre->SetPoint(2,75,0.02729105);
   gre->SetPointError(2,25,0.01554922);
   gre->SetPoint(3,0,0);
   gre->SetPointError(3,0,0);
   
   TH1F *gSyst1__1 = new TH1F("gSyst1__1","Graph",100,0,110);
   gSyst1__1->SetMinimum(0);
   gSyst1__1->SetMaximum(0.0499955);
   gSyst1__1->SetDirectory(0);
   gSyst1__1->SetStats(0);
   gSyst1__1->SetLineStyle(0);
   gSyst1__1->SetLineWidth(2);
   //gSyst1__1->SetMarkerStyle(20);
   gSyst1__1->SetMarkerStyle(1);
   gSyst1__1->GetXaxis()->SetLabelFont(42);
   gSyst1__1->GetXaxis()->SetLabelOffset(0.007);
   gSyst1__1->GetXaxis()->SetLabelSize(0.05);
   gSyst1__1->GetXaxis()->SetTitleSize(0.05);
   gSyst1__1->GetXaxis()->SetTitleOffset(0.9);
   gSyst1__1->GetXaxis()->SetTitleFont(42);
   gSyst1__1->GetYaxis()->SetNdivisions(408);
   gSyst1__1->GetYaxis()->SetLabelFont(42);
   gSyst1__1->GetYaxis()->SetLabelOffset(0.007);
   gSyst1__1->GetYaxis()->SetLabelSize(0.05);
   gSyst1__1->GetYaxis()->SetTitleSize(0.05);
   gSyst1__1->GetYaxis()->SetTitleOffset(1.3);
   gSyst1__1->GetYaxis()->SetTitleFont(42);
   gSyst1__1->GetZaxis()->SetLabelFont(42);
   gSyst1__1->GetZaxis()->SetLabelOffset(0.007);
   gSyst1__1->GetZaxis()->SetLabelSize(0.05);
   gSyst1__1->GetZaxis()->SetTitleSize(0.06);
   gSyst1__1->GetZaxis()->SetTitleFont(42);
   gre->SetHistogram(gSyst1__1);
   
   gre->Draw("2");
   
   TGraphAsymmErrors *grae = new TGraphAsymmErrors(3);
   grae->SetName("Graph_from_hBFractionMC");
   grae->SetTitle("hBFractionMC");
   grae->SetLineColor(2);
   grae->SetLineStyle(0);
   grae->SetLineWidth(2);
   grae->SetMarkerColor(2);
   //grae->SetMarkerStyle(20);
   grae->SetMarkerStyle(1);
   grae->SetPoint(0,10,0.02852294);
   grae->SetPointError(0,0,0,0.0007256208,0.0007256208);
   grae->SetPoint(1,35,0.0276771);
   grae->SetPointError(1,0,0,0.0006088277,0.0006088277);
   grae->SetPoint(2,75,0.02747248);
   grae->SetPointError(2,0,0,0.0006572631,0.0006572631);
   
   TH1F *Graph_from_hBFractionMC1 = new TH1F("Graph_from_hBFractionMC1","hBFractionMC",100,3.5,81.5);
   Graph_from_hBFractionMC1->SetMinimum(0.02657188);
   Graph_from_hBFractionMC1->SetMaximum(0.0294919);
   Graph_from_hBFractionMC1->SetDirectory(0);
   Graph_from_hBFractionMC1->SetStats(0);
   Graph_from_hBFractionMC1->SetLineStyle(0);
   Graph_from_hBFractionMC1->SetLineWidth(2);
   Graph_from_hBFractionMC1->SetMarkerStyle(20);
   Graph_from_hBFractionMC1->GetXaxis()->SetLabelFont(42);
   Graph_from_hBFractionMC1->GetXaxis()->SetLabelOffset(0.007);
   Graph_from_hBFractionMC1->GetXaxis()->SetLabelSize(0.05);
   Graph_from_hBFractionMC1->GetXaxis()->SetTitleSize(0.05);
   Graph_from_hBFractionMC1->GetXaxis()->SetTitleOffset(0.9);
   Graph_from_hBFractionMC1->GetXaxis()->SetTitleFont(42);
   Graph_from_hBFractionMC1->GetYaxis()->SetNdivisions(408);
   Graph_from_hBFractionMC1->GetYaxis()->SetLabelFont(42);
   Graph_from_hBFractionMC1->GetYaxis()->SetLabelOffset(0.007);
   Graph_from_hBFractionMC1->GetYaxis()->SetLabelSize(0.05);
   Graph_from_hBFractionMC1->GetYaxis()->SetTitleSize(0.05);
   Graph_from_hBFractionMC1->GetYaxis()->SetTitleOffset(1.3);
   Graph_from_hBFractionMC1->GetYaxis()->SetTitleFont(42);
   Graph_from_hBFractionMC1->GetZaxis()->SetLabelFont(42);
   Graph_from_hBFractionMC1->GetZaxis()->SetLabelOffset(0.007);
   Graph_from_hBFractionMC1->GetZaxis()->SetLabelSize(0.05);
   Graph_from_hBFractionMC1->GetZaxis()->SetTitleSize(0.06);
   Graph_from_hBFractionMC1->GetZaxis()->SetTitleFont(42);
   grae->SetHistogram(Graph_from_hBFractionMC1);
   
   grae->Draw("z,p,");
   Double_t xAxis2[4] = {0, 20, 50, 100}; 
   
   TH1D *hBFractionMC2 = new TH1D("hBFractionMC2","hBFractionMC",3, xAxis2);
   hBFractionMC2->SetBinContent(1,0.02852294);
   hBFractionMC2->SetBinContent(2,0.0276771);
   hBFractionMC2->SetBinContent(3,0.02747248);
   hBFractionMC2->SetBinError(1,0.0007256208);
   hBFractionMC2->SetBinError(2,0.0006088277);
   hBFractionMC2->SetBinError(3,0.0006572631);
   hBFractionMC2->SetMinimum(0);
   hBFractionMC2->SetMaximum(0.06);
   hBFractionMC2->SetEntries(6);
   hBFractionMC2->SetLineColor(2);
   hBFractionMC2->SetLineStyle(0);
   hBFractionMC2->SetLineWidth(2);
   hBFractionMC2->SetMarkerColor(2);
   hBFractionMC2->SetMarkerStyle(20);
   hBFractionMC2->SetMarkerSize(0);
   hBFractionMC2->GetXaxis()->SetTitle("Centrality");
   hBFractionMC2->GetXaxis()->CenterTitle(true);
   hBFractionMC2->GetXaxis()->SetLabelFont(42);
   hBFractionMC2->GetXaxis()->SetLabelOffset(0.007);
   hBFractionMC2->GetXaxis()->SetLabelSize(0.05);
   hBFractionMC2->GetXaxis()->SetTitleSize(0.05);
   hBFractionMC2->GetXaxis()->SetTitleFont(42);
   hBFractionMC2->GetYaxis()->SetTitle("b-jet fraction");
   hBFractionMC2->GetYaxis()->CenterTitle(true);
   hBFractionMC2->GetYaxis()->SetNdivisions(408);
   hBFractionMC2->GetYaxis()->SetLabelFont(42);
   hBFractionMC2->GetYaxis()->SetLabelOffset(0.007);
   hBFractionMC2->GetYaxis()->SetLabelSize(0.05);
   hBFractionMC2->GetYaxis()->SetTitleSize(0.05);
   hBFractionMC2->GetYaxis()->SetTitleOffset(1.3);
   hBFractionMC2->GetYaxis()->SetTitleFont(42);
   hBFractionMC2->GetZaxis()->SetLabelFont(42);
   hBFractionMC2->GetZaxis()->SetLabelOffset(0.007);
   hBFractionMC2->GetZaxis()->SetLabelSize(0.05);
   hBFractionMC2->GetZaxis()->SetTitleSize(0.06);
   hBFractionMC2->GetZaxis()->SetTitleFont(42);
   hBFractionMC2->Draw("hist,same");
   
   grae = new TGraphAsymmErrors(3);
   grae->SetName("Graph_from_hBFractionDataLTJP");
   grae->SetTitle("hBFractionDataLTJP");
   grae->SetLineStyle(0);
   grae->SetLineWidth(2);
   grae->SetMarkerStyle(8);
   grae->SetMarkerSize(1.5);
   grae->SetPoint(0,10,0.0381308);
   grae->SetPointError(0,0,0,0.002765695,0.002765695);
   grae->SetPoint(1,35,0.02899246);
   grae->SetPointError(1,0,0,0.002657872,0.002657872);
   grae->SetPoint(2,75,0.02729105);
   grae->SetPointError(2,0,0,0.005323763,0.005323763);
   
   TH1F *Graph_from_hBFractionDataLTJP2 = new TH1F("Graph_from_hBFractionDataLTJP2","hBFractionDataLTJP",100,3.5,81.5);
   Graph_from_hBFractionDataLTJP2->SetMinimum(0.02007437);
   Graph_from_hBFractionDataLTJP2->SetMaximum(0.04278942);
   Graph_from_hBFractionDataLTJP2->SetDirectory(0);
   Graph_from_hBFractionDataLTJP2->SetStats(0);
   Graph_from_hBFractionDataLTJP2->SetLineStyle(0);
   Graph_from_hBFractionDataLTJP2->SetLineWidth(2);
   Graph_from_hBFractionDataLTJP2->SetMarkerStyle(20);
   Graph_from_hBFractionDataLTJP2->GetXaxis()->SetLabelFont(42);
   Graph_from_hBFractionDataLTJP2->GetXaxis()->SetLabelOffset(0.007);
   Graph_from_hBFractionDataLTJP2->GetXaxis()->SetLabelSize(0.05);
   Graph_from_hBFractionDataLTJP2->GetXaxis()->SetTitleSize(0.05);
   Graph_from_hBFractionDataLTJP2->GetXaxis()->SetTitleOffset(0.9);
   Graph_from_hBFractionDataLTJP2->GetXaxis()->SetTitleFont(42);
   Graph_from_hBFractionDataLTJP2->GetYaxis()->SetNdivisions(408);
   Graph_from_hBFractionDataLTJP2->GetYaxis()->SetLabelFont(42);
   Graph_from_hBFractionDataLTJP2->GetYaxis()->SetLabelOffset(0.007);
   Graph_from_hBFractionDataLTJP2->GetYaxis()->SetLabelSize(0.05);
   Graph_from_hBFractionDataLTJP2->GetYaxis()->SetTitleSize(0.05);
   Graph_from_hBFractionDataLTJP2->GetYaxis()->SetTitleOffset(1.3);
   Graph_from_hBFractionDataLTJP2->GetYaxis()->SetTitleFont(42);
   Graph_from_hBFractionDataLTJP2->GetZaxis()->SetLabelFont(42);
   Graph_from_hBFractionDataLTJP2->GetZaxis()->SetLabelOffset(0.007);
   Graph_from_hBFractionDataLTJP2->GetZaxis()->SetLabelSize(0.05);
   Graph_from_hBFractionDataLTJP2->GetZaxis()->SetTitleSize(0.06);
   Graph_from_hBFractionDataLTJP2->GetZaxis()->SetTitleFont(42);
   grae->SetHistogram(Graph_from_hBFractionDataLTJP2);
   
   grae->Draw("p,e1,");
   
   TLegend *leg = new TLegend(0.3,0.705,0.965,0.905,NULL,"brNDC");
   leg->SetTextFont(43);
   leg->SetTextSize(23);
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(19);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("NULL","#int L dt = 150 #mub^{-1}","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   //entry->SetTextFont(42);
   entry->SetTextFont(43);
   entry->SetTextSize(23);
   entry=leg->AddEntry("Graph_from_hBFractionDataLTJP","PbPb data","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1.5);
   entry=leg->AddEntry("Graph_from_hBFractionMC","PYTHIA+HYDJET 1.8","lp");
   entry->SetLineColor(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(2);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("gSyst","Sys. uncertainty","f");
   entry->SetFillColor(5);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   Double_t xAxis3[4] = {0, 20, 50, 100}; 
   
   TH1D *hBFractionMC2__2 = new TH1D("hBFractionMC2__2","hBFractionMC",3, xAxis3);
   hBFractionMC2__2->SetBinContent(1,0.02852294);
   hBFractionMC2__2->SetBinContent(2,0.0276771);
   hBFractionMC2__2->SetBinContent(3,0.02747248);
   hBFractionMC2__2->SetBinError(1,0.0007256208);
   hBFractionMC2__2->SetBinError(2,0.0006088277);
   hBFractionMC2__2->SetBinError(3,0.0006572631);
   hBFractionMC2__2->SetMinimum(0);
   hBFractionMC2__2->SetMaximum(0.06);
   hBFractionMC2__2->SetEntries(6);
   hBFractionMC2__2->SetDirectory(0);
   hBFractionMC2__2->SetLineColor(2);
   hBFractionMC2__2->SetLineStyle(0);
   hBFractionMC2__2->SetLineWidth(2);
   hBFractionMC2__2->SetMarkerColor(2);
   hBFractionMC2__2->SetMarkerStyle(20);
   hBFractionMC2__2->SetMarkerSize(0);
   hBFractionMC2__2->GetXaxis()->SetTitle("Centrality");
   hBFractionMC2__2->GetXaxis()->CenterTitle(true);
   hBFractionMC2__2->GetXaxis()->SetLabelFont(42);
   hBFractionMC2__2->GetXaxis()->SetLabelOffset(0.007);
   hBFractionMC2__2->GetXaxis()->SetLabelSize(0.05);
   hBFractionMC2__2->GetXaxis()->SetTitleSize(0.05);
   hBFractionMC2__2->GetXaxis()->SetTitleFont(42);
   hBFractionMC2__2->GetYaxis()->SetTitle("b-jet fraction");
   hBFractionMC2__2->GetYaxis()->CenterTitle(true);
   hBFractionMC2__2->GetYaxis()->SetNdivisions(408);
   hBFractionMC2__2->GetYaxis()->SetLabelFont(42);
   hBFractionMC2__2->GetYaxis()->SetLabelOffset(0.007);
   hBFractionMC2__2->GetYaxis()->SetLabelSize(0.05);
   hBFractionMC2__2->GetYaxis()->SetTitleSize(0.05);
   hBFractionMC2__2->GetYaxis()->SetTitleOffset(1.3);
   hBFractionMC2__2->GetYaxis()->SetTitleFont(42);
   hBFractionMC2__2->GetZaxis()->SetLabelFont(42);
   hBFractionMC2__2->GetZaxis()->SetLabelOffset(0.007);
   hBFractionMC2__2->GetZaxis()->SetLabelSize(0.05);
   hBFractionMC2__2->GetZaxis()->SetTitleSize(0.06);
   hBFractionMC2__2->GetZaxis()->SetTitleFont(42);
   hBFractionMC2__2->Draw("sameaxis");
   cBFraction2->Modified();
   cBFraction2->cd();
   cBFraction2->SetSelected(cBFraction2);
}
