{
//=========Macro generated from canvas: cDR/double ratio
//=========  (Wed Jul 25 09:46:51 2012) by ROOT version5.30/03
   TCanvas *cDR = new TCanvas("cDR", "double ratio",0,908,600,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   cDR->Range(56,-0.3153846,216,2.312821);
   cDR->SetFillColor(0);
   cDR->SetBorderMode(0);
   cDR->SetBorderSize(2);
   cDR->SetTickx(1);
   cDR->SetTicky(1);
   cDR->SetLeftMargin(0.15);
   cDR->SetBottomMargin(0.12);
   cDR->SetFrameBorderMode(0);
   cDR->SetFrameBorderMode(0);
   
   TH1F *hframe = new TH1F("hframe","hframe",1,80,200);
   hframe->SetMinimum(0);
   hframe->SetMaximum(2.05);
   hframe->SetStats(0);
   hframe->GetXaxis()->SetTitle("Jet p_{T} (GeV/c)");
   hframe->GetXaxis()->SetLabelFont(42);
   hframe->GetXaxis()->SetLabelSize(0.05);
   hframe->GetXaxis()->SetTitleSize(0.05);
   hframe->GetXaxis()->SetTitleFont(42);
   hframe->GetYaxis()->SetTitle("PbPb b-jet fraction / pp b-jet fraction");
   hframe->GetYaxis()->SetNdivisions(408);
   hframe->GetYaxis()->SetLabelFont(42);
   hframe->GetYaxis()->SetLabelSize(0.05);
   hframe->GetYaxis()->SetTitleSize(0.05);
   hframe->GetYaxis()->SetTitleOffset(1.3);
   hframe->GetYaxis()->SetTitleFont(42);
   hframe->GetZaxis()->SetLabelFont(42);
   hframe->GetZaxis()->SetTitleFont(42);
   hframe->Draw("");
   
   TGraphAsymmErrors *grae = new TGraphAsymmErrors(3);
   grae->SetName("Graph");
   grae->SetTitle("Graph");
   grae->SetFillColor(5);
   grae->SetPoint(0,88.39,1.612389);
   grae->SetPointError(0,8.389999,11.61,0.3869833,0.3869833);
   grae->SetPoint(1,108.3,0.9570809);
   grae->SetPointError(1,8.300003,11.7,0.334029,0.334029);
   grae->SetPoint(2,141,1.02703);
   grae->SetPointError(2,21,59,0.4175152,0.4175152);
   
   TH1F *Graph_Graph1 = new TH1F("Graph_Graph1","Graph",100,68,212);
   Graph_Graph1->SetMinimum(0.4705292);
   Graph_Graph1->SetMaximum(2.138358);
   Graph_Graph1->SetDirectory(0);
   Graph_Graph1->SetStats(0);
   Graph_Graph1->GetXaxis()->SetLabelFont(42);
   Graph_Graph1->GetXaxis()->SetLabelSize(0.05);
   Graph_Graph1->GetXaxis()->SetTitleSize(0.05);
   Graph_Graph1->GetXaxis()->SetTitleFont(42);
   Graph_Graph1->GetYaxis()->SetNdivisions(408);
   Graph_Graph1->GetYaxis()->SetLabelFont(42);
   Graph_Graph1->GetYaxis()->SetLabelSize(0.05);
   Graph_Graph1->GetYaxis()->SetTitleSize(0.05);
   Graph_Graph1->GetYaxis()->SetTitleOffset(1.3);
   Graph_Graph1->GetYaxis()->SetTitleFont(42);
   Graph_Graph1->GetZaxis()->SetLabelFont(42);
   Graph_Graph1->GetZaxis()->SetTitleFont(42);
   grae->SetHistogram(Graph_Graph1);
   
   grae->Draw("2,");
   
   grae = new TGraphAsymmErrors(3);
   grae->SetName("Graph");
   grae->SetTitle("Graph");
   grae->SetFillColor(1);
   grae->SetMarkerStyle(8);
   grae->SetMarkerSize(1.5);
   grae->SetPoint(0,88.39,1.612389);
   grae->SetPointError(0,0,0,0.2079599,0.2079599);
   grae->SetPoint(1,108.3,0.9570809);
   grae->SetPointError(1,0,0,0.1878277,0.1878277);
   grae->SetPoint(2,141,1.02703);
   grae->SetPointError(2,0,0,0.2514591,0.2514591);
   
   TH1F *Graph_Graph2 = new TH1F("Graph_Graph2","Graph",100,83.129,146.261);
   Graph_Graph2->SetMinimum(0.6641436);
   Graph_Graph2->SetMaximum(1.925459);
   Graph_Graph2->SetDirectory(0);
   Graph_Graph2->SetStats(0);
   Graph_Graph2->GetXaxis()->SetLabelFont(42);
   Graph_Graph2->GetXaxis()->SetLabelSize(0.05);
   Graph_Graph2->GetXaxis()->SetTitleSize(0.05);
   Graph_Graph2->GetXaxis()->SetTitleFont(42);
   Graph_Graph2->GetYaxis()->SetNdivisions(408);
   Graph_Graph2->GetYaxis()->SetLabelFont(42);
   Graph_Graph2->GetYaxis()->SetLabelSize(0.05);
   Graph_Graph2->GetYaxis()->SetTitleSize(0.05);
   Graph_Graph2->GetYaxis()->SetTitleOffset(1.3);
   Graph_Graph2->GetYaxis()->SetTitleFont(42);
   Graph_Graph2->GetZaxis()->SetLabelFont(42);
   Graph_Graph2->GetZaxis()->SetTitleFont(42);
   grae->SetHistogram(Graph_Graph2);
   
   grae->Draw("p");
   
   TH1F *hframe__1 = new TH1F("hframe__1","hframe",1,80,200);
   hframe__1->SetMinimum(0);
   hframe__1->SetMaximum(2.05);
   hframe__1->SetDirectory(0);
   hframe__1->SetStats(0);
   hframe__1->GetXaxis()->SetTitle("Jet p_{T} (GeV/c)");
   hframe__1->GetXaxis()->SetLabelFont(42);
   hframe__1->GetXaxis()->SetLabelSize(0.05);
   hframe__1->GetXaxis()->SetTitleSize(0.05);
   hframe__1->GetXaxis()->SetTitleFont(42);
   hframe__1->GetYaxis()->SetTitle("PbPb b-jet fraction / pp b-jet fraction");
   hframe__1->GetYaxis()->SetNdivisions(408);
   hframe__1->GetYaxis()->SetLabelFont(42);
   hframe__1->GetYaxis()->SetLabelSize(0.05);
   hframe__1->GetYaxis()->SetTitleSize(0.05);
   hframe__1->GetYaxis()->SetTitleOffset(1.3);
   hframe__1->GetYaxis()->SetTitleFont(42);
   hframe__1->GetZaxis()->SetLabelFont(42);
   hframe__1->GetZaxis()->SetTitleFont(42);
   hframe__1->Draw("sameaxis");
   TLatex *   tex = new TLatex(83,2.12,"CMS preliminary");
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(147,2.12,"#sqrt{s_{NN}} = 2.76 TeV");
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TLegend *leg = new TLegend(0.2,0.15,1.02,0.34,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(19);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("NULL","#int L dt = 150 #mub^{-1} (PbPb), 231 nb^{-1} (pp) ","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Graph","Data","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1.5);
   entry=leg->AddEntry("Graph","Exp. uncertainty","f");
   entry->SetFillColor(5);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   cDR->Modified();
   cDR->cd();
   cDR->SetSelected(cDR);
}
