{
//=========Macro generated from canvas: cDR/double ratio
//=========  (Thu Jul 26 19:12:30 2012) by ROOT version5.26/00
   TCanvas *cDR = new TCanvas("cDR", "double ratio",0,22,700,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   cDR->Range(54.28572,-0.2963855,225.7143,2.173494);
   cDR->SetFillColor(0);
   cDR->SetBorderMode(0);
   cDR->SetBorderSize(2);
   cDR->SetTickx(1);
   cDR->SetTicky(1);
   cDR->SetLeftMargin(0.15);
   cDR->SetRightMargin(0.15);
   cDR->SetTopMargin(0.05);
   cDR->SetBottomMargin(0.12);
   cDR->SetFrameFillStyle(0);
   cDR->SetFrameBorderMode(0);
   cDR->SetFrameFillStyle(0);
   cDR->SetFrameBorderMode(0);
   
   TH1F *hframe = new TH1F("hframe","hframe",1,80,200);
   hframe->SetMinimum(0);
   hframe->SetMaximum(2.05);
   hframe->SetLineStyle(0);
   hframe->SetLineWidth(2);
   hframe->SetMarkerStyle(20);
   hframe->GetXaxis()->SetTitle("Jet p_{T} (GeV/c)");
   hframe->GetXaxis()->CenterTitle(true);
   hframe->GetXaxis()->SetLabelFont(43);
   hframe->GetXaxis()->SetLabelOffset(0.007);
   hframe->GetXaxis()->SetLabelSize(28);
   hframe->GetXaxis()->SetTitleSize(28);
   hframe->GetXaxis()->SetTitleOffset(1.1);
   hframe->GetXaxis()->SetTitleFont(43);
   hframe->GetYaxis()->SetTitle("PbPb b-jet fraction / pp b-jet fraction");
   hframe->GetYaxis()->CenterTitle(true);
   hframe->GetYaxis()->SetNdivisions(408);
   hframe->GetYaxis()->SetLabelFont(43);
   hframe->GetYaxis()->SetLabelOffset(0.007);
   hframe->GetYaxis()->SetLabelSize(28);
   hframe->GetYaxis()->SetTitleSize(28);
   hframe->GetYaxis()->SetTitleOffset(1.25);
   hframe->GetYaxis()->SetTitleFont(43);
   hframe->GetZaxis()->SetLabelFont(43);
   hframe->GetZaxis()->SetLabelOffset(0.007);
   hframe->GetZaxis()->SetLabelSize(28);
   hframe->GetZaxis()->SetTitleSize(0.06);
   hframe->GetZaxis()->SetTitleFont(43);
   hframe->Draw("");
   
   TGraphAsymmErrors *grae = new TGraphAsymmErrors(3);
   grae->SetName("Graph");
   grae->SetTitle("Graph");
   grae->SetFillColor(5);
   grae->SetMarkerStyle(20);
   grae->SetPoint(0,88.39,1.612389);
   grae->SetPointError(0,8.389999,11.61,0.3869833,0.3869833);
   grae->SetPoint(1,108.3,0.9570809);
   grae->SetPointError(1,8.300003,11.7,0.334029,0.334029);
   grae->SetPoint(2,141,1.02703);
   grae->SetPointError(2,21,59,0.4175152,0.4175152);
   
   TH1F *Graph1 = new TH1F("Graph1","Graph",100,68,212);
   Graph1->SetMinimum(0.4705292);
   Graph1->SetMaximum(2.138358);
   Graph1->SetDirectory(0);
   Graph1->SetStats(0);
   Graph1->SetLineStyle(0);
   Graph1->SetLineWidth(2);
   Graph1->SetMarkerStyle(20);
   Graph1->GetXaxis()->SetLabelFont(43);
   Graph1->GetXaxis()->SetLabelOffset(0.007);
   Graph1->GetXaxis()->SetLabelSize(28);
   Graph1->GetXaxis()->SetTitleSize(28);
   Graph1->GetXaxis()->SetTitleOffset(1.1);
   Graph1->GetXaxis()->SetTitleFont(43);
   Graph1->GetYaxis()->SetNdivisions(408);
   Graph1->GetYaxis()->SetLabelFont(43);
   Graph1->GetYaxis()->SetLabelOffset(0.007);
   Graph1->GetYaxis()->SetLabelSize(28);
   Graph1->GetYaxis()->SetTitleSize(28);
   Graph1->GetYaxis()->SetTitleOffset(1.25);
   Graph1->GetYaxis()->SetTitleFont(43);
   Graph1->GetZaxis()->SetLabelFont(43);
   Graph1->GetZaxis()->SetLabelOffset(0.007);
   Graph1->GetZaxis()->SetLabelSize(28);
   Graph1->GetZaxis()->SetTitleSize(0.06);
   Graph1->GetZaxis()->SetTitleFont(43);
   grae->SetHistogram(Graph1);
   
   grae->Draw("2,");
   
   grae = new TGraphAsymmErrors(3);
   grae->SetName("Graph");
   grae->SetTitle("Graph");
   grae->SetFillColor(1);
   grae->SetMarkerStyle(8);
   grae->SetMarkerSize(1.3);
   grae->SetPoint(0,88.39,1.612389);
   grae->SetPointError(0,0,0,0.2079599,0.2079599);
   grae->SetPoint(1,108.3,0.9570809);
   grae->SetPointError(1,0,0,0.1878277,0.1878277);
   grae->SetPoint(2,141,1.02703);
   grae->SetPointError(2,0,0,0.2514591,0.2514591);
   
   TH1F *Graph2 = new TH1F("Graph2","Graph",100,83.129,146.261);
   Graph2->SetMinimum(0.6641436);
   Graph2->SetMaximum(1.925459);
   Graph2->SetDirectory(0);
   Graph2->SetStats(0);
   Graph2->SetLineStyle(0);
   Graph2->SetLineWidth(2);
   Graph2->SetMarkerStyle(20);
   Graph2->GetXaxis()->SetLabelFont(43);
   Graph2->GetXaxis()->SetLabelOffset(0.007);
   Graph2->GetXaxis()->SetLabelSize(28);
   Graph2->GetXaxis()->SetTitleSize(28);
   Graph2->GetXaxis()->SetTitleOffset(1.1);
   Graph2->GetXaxis()->SetTitleFont(43);
   Graph2->GetYaxis()->SetNdivisions(408);
   Graph2->GetYaxis()->SetLabelFont(43);
   Graph2->GetYaxis()->SetLabelOffset(0.007);
   Graph2->GetYaxis()->SetLabelSize(28);
   Graph2->GetYaxis()->SetTitleSize(28);
   Graph2->GetYaxis()->SetTitleOffset(1.25);
   Graph2->GetYaxis()->SetTitleFont(43);
   Graph2->GetZaxis()->SetLabelFont(43);
   Graph2->GetZaxis()->SetLabelOffset(0.007);
   Graph2->GetZaxis()->SetLabelSize(28);
   Graph2->GetZaxis()->SetTitleSize(0.06);
   Graph2->GetZaxis()->SetTitleFont(43);
   grae->SetHistogram(Graph2);
   
   //grae->Draw("z,p");
   grae->Draw("p");
   
   TH1F *hframe__1 = new TH1F("hframe__1","hframe",1,80,200);
   hframe__1->SetMinimum(0);
   hframe__1->SetMaximum(2.05);
   hframe__1->SetDirectory(0);
   hframe__1->SetLineStyle(0);
   hframe__1->SetLineWidth(2);
   hframe__1->SetMarkerStyle(20);
   hframe__1->GetXaxis()->SetTitle("Jet p_{T} (GeV/c)");
   hframe__1->GetXaxis()->CenterTitle(true);
   hframe__1->GetXaxis()->SetLabelFont(43);
   hframe__1->GetXaxis()->SetLabelOffset(0.007);
   hframe__1->GetXaxis()->SetLabelSize(28);
   hframe__1->GetXaxis()->SetTitleSize(28);
   hframe__1->GetXaxis()->SetTitleOffset(1.1);
   hframe__1->GetXaxis()->SetTitleFont(43);
   hframe__1->GetYaxis()->SetTitle("PbPb b-jet fraction / pp b-jet fraction");
   hframe__1->GetYaxis()->CenterTitle(true);
   hframe__1->GetYaxis()->SetNdivisions(408);
   hframe__1->GetYaxis()->SetLabelFont(43);
   hframe__1->GetYaxis()->SetLabelOffset(0.007);
   hframe__1->GetYaxis()->SetLabelSize(28);
   hframe__1->GetYaxis()->SetTitleSize(28);
   hframe__1->GetYaxis()->SetTitleOffset(1.25);
   hframe__1->GetYaxis()->SetTitleFont(43);
   hframe__1->GetZaxis()->SetLabelFont(43);
   hframe__1->GetZaxis()->SetLabelOffset(0.007);
   hframe__1->GetZaxis()->SetLabelSize(28);
   hframe__1->GetZaxis()->SetTitleSize(0.06);
   hframe__1->GetZaxis()->SetTitleFont(43);
   hframe__1->Draw("sameaxis");
   TLatex *   tex = new TLatex(81,2.087,"CMS Preliminary");
   tex->SetTextFont(43);
   tex->SetTextSize(23);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(160,2.087,"#sqrt{s_{NN}} = 2.76 TeV");
   tex->SetTextFont(43);
   tex->SetTextSize(23);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TLegend *leg = new TLegend(0.2,0.15,0.99,0.34,NULL,"brNDC");
   leg->SetTextFont(43);
   leg->SetTextSize(23);
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(19);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("NULL","#int L dt = 150 #mub^{-1} (PbPb), 231 nb^{-1} (pp) ","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   //entry->SetTextFont(43);
   entry=leg->AddEntry("Graph","Data","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1.3);
   entry=leg->AddEntry("Graph","Sys. uncertainty","f");
   entry->SetFillColor(5);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   cDR->Modified();
   cDR->cd();
   cDR->SetSelected(cDR);
}
