{
//=========Macro generated from canvas: cBEfficiency/b purity
//=========  (Thu Jul 26 19:45:29 2012) by ROOT version5.26/00
   TCanvas *cBEfficiency = new TCanvas("cBEfficiency", "b purity",340,22,700,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   cBEfficiency->Range(54.28572,-0.1445783,225.7143,1.060241);
   cBEfficiency->SetFillColor(0);
   cBEfficiency->SetBorderMode(0);
   cBEfficiency->SetBorderSize(2);
   cBEfficiency->SetTickx(1);
   cBEfficiency->SetTicky(1);
   cBEfficiency->SetLeftMargin(0.15);
   cBEfficiency->SetRightMargin(0.15);
   cBEfficiency->SetTopMargin(0.05);
   cBEfficiency->SetBottomMargin(0.12);
   cBEfficiency->SetFrameFillStyle(0);
   cBEfficiency->SetFrameBorderMode(0);
   cBEfficiency->SetFrameFillStyle(0);
   cBEfficiency->SetFrameBorderMode(0);
   Double_t xAxis1[5] = {80, 100, 120, 150, 200}; 
   
   TH1D *hBEfficiencyMC = new TH1D("hBEfficiencyMC","hBEfficiencyMC",4, xAxis1);
   hBEfficiencyMC->SetBinContent(1,0.4544577);
   hBEfficiencyMC->SetBinContent(2,0.4630344);
   hBEfficiencyMC->SetBinContent(3,0.4320425);
   hBEfficiencyMC->SetBinContent(4,0.4465532);
   hBEfficiencyMC->SetBinError(1,0.00695987);
   hBEfficiencyMC->SetBinError(2,0.009712577);
   hBEfficiencyMC->SetBinError(3,0.009675435);
   hBEfficiencyMC->SetBinError(4,0.01202189);
   hBEfficiencyMC->SetMinimum(0);
   hBEfficiencyMC->SetMaximum(1);
   hBEfficiencyMC->SetEntries(4);
   hBEfficiencyMC->SetStats(0);
   hBEfficiencyMC->SetLineColor(0);
   hBEfficiencyMC->SetLineStyle(0);
   hBEfficiencyMC->SetLineWidth(2);
   hBEfficiencyMC->SetMarkerStyle(20);
   hBEfficiencyMC->SetMarkerSize(0);
   hBEfficiencyMC->GetXaxis()->SetTitle("Jet p_{T} (GeV/c)");
   hBEfficiencyMC->GetXaxis()->CenterTitle(true);
   hBEfficiencyMC->GetXaxis()->SetLabelFont(43);
   hBEfficiencyMC->GetXaxis()->SetLabelOffset(0.007);
   hBEfficiencyMC->GetXaxis()->SetLabelSize(28);
   hBEfficiencyMC->GetXaxis()->SetTitleSize(28);
   hBEfficiencyMC->GetXaxis()->SetTitleOffset(1.1);
   hBEfficiencyMC->GetXaxis()->SetTitleFont(43);
   hBEfficiencyMC->GetYaxis()->SetTitle("b-jet efficiency");
   hBEfficiencyMC->GetYaxis()->CenterTitle(true);
   hBEfficiencyMC->GetYaxis()->SetNdivisions(408);
   hBEfficiencyMC->GetYaxis()->SetLabelFont(43);
   hBEfficiencyMC->GetYaxis()->SetLabelOffset(0.007);
   hBEfficiencyMC->GetYaxis()->SetLabelSize(28);
   hBEfficiencyMC->GetYaxis()->SetTitleSize(28);
   hBEfficiencyMC->GetYaxis()->SetTitleOffset(1.3);
   hBEfficiencyMC->GetYaxis()->SetTitleFont(43);
   hBEfficiencyMC->GetZaxis()->SetLabelFont(43);
   hBEfficiencyMC->GetZaxis()->SetLabelOffset(0.007);
   hBEfficiencyMC->GetZaxis()->SetLabelSize(28);
   hBEfficiencyMC->GetZaxis()->SetTitleSize(0.06);
   hBEfficiencyMC->GetZaxis()->SetTitleFont(43);
   hBEfficiencyMC->Draw("");
   
   TGraphAsymmErrors *grae = new TGraphAsymmErrors(4);
   grae->SetName("Graph_from_hBEfficiencyDataLTJP");
   grae->SetTitle("hBEfficiencyDataLTJP");
   grae->SetFillColor(1);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#00cc00");
   grae->SetLineColor(kGreen+2);

   ci = TColor::GetColor("#00cc00");
   grae->SetMarkerColor(kGreen+2);
   grae->SetMarkerStyle(25);
   grae->SetMarkerSize(1.5);
   grae->SetPoint(0,88.39,0.4329426);
   grae->SetPointError(0,0,0,0.01421555,0.01421555);
   grae->SetPoint(1,108.3,0.4233334);
   grae->SetPointError(1,0,0,0.02552132,0.02552132);
   grae->SetPoint(2,131.7,0.4672852);
   grae->SetPointError(2,0,0,0.03530586,0.03530586);
   grae->SetPoint(3,167.5,0.4270522);
   grae->SetPointError(3,0,0,0.07398794,0.07398794);
   
   TH1F *Graph_Graph_from_hBEfficiencyDataLTJP11 = new TH1F("Graph_Graph_from_hBEfficiencyDataLTJP11","hBEfficiencyDataLTJP",100,80.479,175.411);
   Graph_Graph_from_hBEfficiencyDataLTJP11->SetMinimum(0.3381116);
   Graph_Graph_from_hBEfficiencyDataLTJP11->SetMaximum(0.5175437);
   Graph_Graph_from_hBEfficiencyDataLTJP11->SetDirectory(0);
   Graph_Graph_from_hBEfficiencyDataLTJP11->SetStats(0);
   Graph_Graph_from_hBEfficiencyDataLTJP11->SetLineStyle(0);
   Graph_Graph_from_hBEfficiencyDataLTJP11->SetLineWidth(2);
   Graph_Graph_from_hBEfficiencyDataLTJP11->SetMarkerStyle(20);
   Graph_Graph_from_hBEfficiencyDataLTJP11->GetXaxis()->SetLabelFont(43);
   Graph_Graph_from_hBEfficiencyDataLTJP11->GetXaxis()->SetLabelOffset(0.007);
   Graph_Graph_from_hBEfficiencyDataLTJP11->GetXaxis()->SetLabelSize(28);
   Graph_Graph_from_hBEfficiencyDataLTJP11->GetXaxis()->SetTitleSize(28);
   Graph_Graph_from_hBEfficiencyDataLTJP11->GetXaxis()->SetTitleOffset(1.1);
   Graph_Graph_from_hBEfficiencyDataLTJP11->GetXaxis()->SetTitleFont(43);
   Graph_Graph_from_hBEfficiencyDataLTJP11->GetYaxis()->SetNdivisions(408);
   Graph_Graph_from_hBEfficiencyDataLTJP11->GetYaxis()->SetLabelFont(43);
   Graph_Graph_from_hBEfficiencyDataLTJP11->GetYaxis()->SetLabelOffset(0.007);
   Graph_Graph_from_hBEfficiencyDataLTJP11->GetYaxis()->SetLabelSize(28);
   Graph_Graph_from_hBEfficiencyDataLTJP11->GetYaxis()->SetTitleSize(28);
   Graph_Graph_from_hBEfficiencyDataLTJP11->GetYaxis()->SetTitleOffset(1.3);
   Graph_Graph_from_hBEfficiencyDataLTJP11->GetYaxis()->SetTitleFont(43);
   Graph_Graph_from_hBEfficiencyDataLTJP11->GetZaxis()->SetLabelFont(43);
   Graph_Graph_from_hBEfficiencyDataLTJP11->GetZaxis()->SetLabelOffset(0.007);
   Graph_Graph_from_hBEfficiencyDataLTJP11->GetZaxis()->SetLabelSize(28);
   Graph_Graph_from_hBEfficiencyDataLTJP11->GetZaxis()->SetTitleSize(0.06);
   Graph_Graph_from_hBEfficiencyDataLTJP11->GetZaxis()->SetTitleFont(43);
   grae->SetHistogram(Graph_Graph_from_hBEfficiencyDataLTJP11);
   
   grae->Draw("p,");
   
   grae = new TGraphAsymmErrors(4);
   grae->SetName("Graph_from_hBEfficiencyMC");
   grae->SetTitle("hBEfficiencyMC");
   grae->SetFillColor(1);
   grae->SetLineColor(2);
   grae->SetMarkerColor(2);
   grae->SetMarkerStyle(20);
   grae->SetMarkerSize(1.2);
   grae->SetPoint(0,88.24,0.4544577);
   grae->SetPointError(0,0,0,0.00695987,0.00695987);
   grae->SetPoint(1,108.1,0.4630344);
   grae->SetPointError(1,0,0,0.009712577,0.009712577);
   grae->SetPoint(2,131.5,0.4320425);
   grae->SetPointError(2,0,0,0.009675435,0.009675435);
   grae->SetPoint(3,167,0.4465532);
   grae->SetPointError(3,0,0,0.01202189,0.01202189);
   
   TH1F *Graph_Graph_from_hBEfficiencyMC22 = new TH1F("Graph_Graph_from_hBEfficiencyMC22","hBEfficiencyMC",100,80.364,174.876);
   Graph_Graph_from_hBEfficiencyMC22->SetMinimum(0.4173291);
   Graph_Graph_from_hBEfficiencyMC22->SetMaximum(0.477785);
   Graph_Graph_from_hBEfficiencyMC22->SetDirectory(0);
   Graph_Graph_from_hBEfficiencyMC22->SetStats(0);
   Graph_Graph_from_hBEfficiencyMC22->SetLineStyle(0);
   Graph_Graph_from_hBEfficiencyMC22->SetLineWidth(2);
   Graph_Graph_from_hBEfficiencyMC22->SetMarkerStyle(20);
   Graph_Graph_from_hBEfficiencyMC22->GetXaxis()->SetLabelFont(43);
   Graph_Graph_from_hBEfficiencyMC22->GetXaxis()->SetLabelOffset(0.007);
   Graph_Graph_from_hBEfficiencyMC22->GetXaxis()->SetLabelSize(28);
   Graph_Graph_from_hBEfficiencyMC22->GetXaxis()->SetTitleSize(28);
   Graph_Graph_from_hBEfficiencyMC22->GetXaxis()->SetTitleOffset(1.1);
   Graph_Graph_from_hBEfficiencyMC22->GetXaxis()->SetTitleFont(43);
   Graph_Graph_from_hBEfficiencyMC22->GetYaxis()->SetNdivisions(408);
   Graph_Graph_from_hBEfficiencyMC22->GetYaxis()->SetLabelFont(43);
   Graph_Graph_from_hBEfficiencyMC22->GetYaxis()->SetLabelOffset(0.007);
   Graph_Graph_from_hBEfficiencyMC22->GetYaxis()->SetLabelSize(28);
   Graph_Graph_from_hBEfficiencyMC22->GetYaxis()->SetTitleSize(28);
   Graph_Graph_from_hBEfficiencyMC22->GetYaxis()->SetTitleOffset(1.3);
   Graph_Graph_from_hBEfficiencyMC22->GetYaxis()->SetTitleFont(43);
   Graph_Graph_from_hBEfficiencyMC22->GetZaxis()->SetLabelFont(43);
   Graph_Graph_from_hBEfficiencyMC22->GetZaxis()->SetLabelOffset(0.007);
   Graph_Graph_from_hBEfficiencyMC22->GetZaxis()->SetLabelSize(28);
   Graph_Graph_from_hBEfficiencyMC22->GetZaxis()->SetTitleSize(0.06);
   Graph_Graph_from_hBEfficiencyMC22->GetZaxis()->SetTitleFont(43);
   grae->SetHistogram(Graph_Graph_from_hBEfficiencyMC22);
   
   grae->Draw("p,");
   
   TLegend *leg = new TLegend(0.25,0.6,0.8,0.8,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(43);
   leg->SetTextSize(23);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(19);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("NULL","PbPb, #int L dt = 150 #mub^{-1}","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   //entry->SetTextFont(43);
   entry=leg->AddEntry("Graph_from_hBEfficiencyMC","Simulation","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(2);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.2);
   //entry->SetTextFont(43);
   entry=leg->AddEntry("Graph_from_hBEfficiencyDataLTJP","Reference tagger","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#00cc00");
   entry->SetMarkerColor(kGreen+2);
   entry->SetMarkerStyle(25);
   entry->SetMarkerSize(1.5);
   //entry->SetTextFont(43);
   leg->Draw();
   TLatex *   tex = new TLatex(90,0.05,"Centrality 0-100%");
   tex->SetTextFont(43);
   tex->SetTextFont(23);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(81,1.02,"CMS Preliminary");
   tex->SetTextFont(43);
   tex->SetTextSize(23);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(160,1.02,"#sqrt{s_{NN}} = 2.76 TeV");
   tex->SetTextFont(43);
   tex->SetTextSize(23);
   tex->SetLineWidth(2);
   tex->Draw();
   cBEfficiency->Modified();
   cBEfficiency->cd();
   cBEfficiency->SetSelected(cBEfficiency);
}
