{
//=========Macro generated from canvas: cBPurity/b purity
//=========  (Thu Jul 26 19:45:24 2012) by ROOT version5.26/00
   TCanvas *cBPurity = new TCanvas("cBPurity", "b purity",0,22,700,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   cBPurity->Range(54.28572,-0.1445783,225.7143,1.060241);
   cBPurity->SetFillColor(0);
   cBPurity->SetBorderMode(0);
   cBPurity->SetBorderSize(2);
   cBPurity->SetTickx(1);
   cBPurity->SetTicky(1);
   cBPurity->SetLeftMargin(0.15);
   cBPurity->SetRightMargin(0.15);
   cBPurity->SetTopMargin(0.05);
   cBPurity->SetBottomMargin(0.12);
   cBPurity->SetFrameFillStyle(0);
   cBPurity->SetFrameBorderMode(0);
   cBPurity->SetFrameFillStyle(0);
   cBPurity->SetFrameBorderMode(0);
   Double_t xAxis1[5] = {80, 100, 120, 150, 200}; 
   
   TH1D *hBPurityMC = new TH1D("hBPurityMC","hBPurityMC",4, xAxis1);
   hBPurityMC->SetBinContent(1,0.313451);
   hBPurityMC->SetBinContent(2,0.3350562);
   hBPurityMC->SetBinContent(3,0.2818521);
   hBPurityMC->SetBinContent(4,0.3212801);
   hBPurityMC->SetBinError(1,0.01914956);
   hBPurityMC->SetBinError(2,0.02336008);
   hBPurityMC->SetBinError(3,0.02876437);
   hBPurityMC->SetBinError(4,0.02144415);
   hBPurityMC->SetMinimum(0);
   hBPurityMC->SetMaximum(1);
   hBPurityMC->SetEntries(4);
   hBPurityMC->SetStats(0);
   hBPurityMC->SetLineColor(0);
   hBPurityMC->SetLineStyle(0);
   hBPurityMC->SetLineWidth(2);
   hBPurityMC->SetMarkerStyle(20);
   hBPurityMC->SetMarkerSize(0);
   hBPurityMC->GetXaxis()->SetTitle("Jet p_{T} (GeV/c)");
   hBPurityMC->GetXaxis()->CenterTitle(true);
   hBPurityMC->GetXaxis()->SetLabelFont(42);
   hBPurityMC->GetXaxis()->SetLabelOffset(0.007);
   hBPurityMC->GetXaxis()->SetLabelSize(0.05);
   hBPurityMC->GetXaxis()->SetTitleSize(0.05);
   hBPurityMC->GetXaxis()->SetTitleOffset(1.1);
   hBPurityMC->GetXaxis()->SetTitleFont(42);
   hBPurityMC->GetYaxis()->SetTitle("b-jet purity");
   hBPurityMC->GetYaxis()->CenterTitle(true);
   hBPurityMC->GetYaxis()->SetNdivisions(408);
   hBPurityMC->GetYaxis()->SetLabelFont(42);
   hBPurityMC->GetYaxis()->SetLabelOffset(0.007);
   hBPurityMC->GetYaxis()->SetLabelSize(0.05);
   hBPurityMC->GetYaxis()->SetTitleSize(0.05);
   hBPurityMC->GetYaxis()->SetTitleOffset(1.3);
   hBPurityMC->GetYaxis()->SetTitleFont(42);
   hBPurityMC->GetZaxis()->SetLabelFont(42);
   hBPurityMC->GetZaxis()->SetLabelOffset(0.007);
   hBPurityMC->GetZaxis()->SetLabelSize(0.05);
   hBPurityMC->GetZaxis()->SetTitleSize(0.06);
   hBPurityMC->GetZaxis()->SetTitleFont(42);
   hBPurityMC->Draw("");
   
   TGraphAsymmErrors *grae = new TGraphAsymmErrors(4);
   grae->SetName("Graph_from_hBPurityData");
   grae->SetTitle("hBPurityData");
   grae->SetFillColor(1);
   grae->SetMarkerStyle(25);
   grae->SetMarkerSize(1.5);
   grae->SetPoint(0,88.39,0.3359805);
   grae->SetPointError(0,0,0,0.01027457,0.01027457);
   grae->SetPoint(1,108.3,0.2856717);
   grae->SetPointError(1,0,0,0.01783066,0.01783066);
   grae->SetPoint(2,131.7,0.3880775);
   grae->SetPointError(2,0,0,0.0280043,0.0280043);
   grae->SetPoint(3,167.5,0.3358413);
   grae->SetPointError(3,0,0,0.05077741,0.05077741);
   
   TH1F *Graph_Graph_from_hBPurityData31 = new TH1F("Graph_Graph_from_hBPurityData31","hBPurityData",100,80.479,175.411);
   Graph_Graph_from_hBPurityData31->SetMinimum(0.2530169);
   Graph_Graph_from_hBPurityData31->SetMaximum(0.4309059);
   Graph_Graph_from_hBPurityData31->SetDirectory(0);
   Graph_Graph_from_hBPurityData31->SetStats(0);
   Graph_Graph_from_hBPurityData31->SetLineStyle(0);
   Graph_Graph_from_hBPurityData31->SetLineWidth(2);
   Graph_Graph_from_hBPurityData31->SetMarkerStyle(20);
   Graph_Graph_from_hBPurityData31->GetXaxis()->SetLabelFont(42);
   Graph_Graph_from_hBPurityData31->GetXaxis()->SetLabelOffset(0.007);
   Graph_Graph_from_hBPurityData31->GetXaxis()->SetLabelSize(0.05);
   Graph_Graph_from_hBPurityData31->GetXaxis()->SetTitleSize(0.05);
   Graph_Graph_from_hBPurityData31->GetXaxis()->SetTitleOffset(1.1);
   Graph_Graph_from_hBPurityData31->GetXaxis()->SetTitleFont(42);
   Graph_Graph_from_hBPurityData31->GetYaxis()->SetNdivisions(408);
   Graph_Graph_from_hBPurityData31->GetYaxis()->SetLabelFont(42);
   Graph_Graph_from_hBPurityData31->GetYaxis()->SetLabelOffset(0.007);
   Graph_Graph_from_hBPurityData31->GetYaxis()->SetLabelSize(0.05);
   Graph_Graph_from_hBPurityData31->GetYaxis()->SetTitleSize(0.05);
   Graph_Graph_from_hBPurityData31->GetYaxis()->SetTitleOffset(1.3);
   Graph_Graph_from_hBPurityData31->GetYaxis()->SetTitleFont(42);
   Graph_Graph_from_hBPurityData31->GetZaxis()->SetLabelFont(42);
   Graph_Graph_from_hBPurityData31->GetZaxis()->SetLabelOffset(0.007);
   Graph_Graph_from_hBPurityData31->GetZaxis()->SetLabelSize(0.05);
   Graph_Graph_from_hBPurityData31->GetZaxis()->SetTitleSize(0.06);
   Graph_Graph_from_hBPurityData31->GetZaxis()->SetTitleFont(42);
   grae->SetHistogram(Graph_Graph_from_hBPurityData31);
   
   grae->Draw("p,");
   
   grae = new TGraphAsymmErrors(4);
   grae->SetName("Graph_from_hBPurityMC");
   grae->SetTitle("hBPurityMC");
   grae->SetFillColor(1);
   grae->SetLineColor(2);
   grae->SetMarkerColor(2);
   grae->SetMarkerStyle(20);
   grae->SetMarkerSize(1.2);
   grae->SetPoint(0,88.24,0.313451);
   grae->SetPointError(0,0,0,0.01914956,0.01914956);
   grae->SetPoint(1,108.1,0.3350562);
   grae->SetPointError(1,0,0,0.02336008,0.02336008);
   grae->SetPoint(2,131.5,0.2818521);
   grae->SetPointError(2,0,0,0.02876437,0.02876437);
   grae->SetPoint(3,167,0.3212801);
   grae->SetPointError(3,0,0,0.02144415,0.02144415);
   
   TH1F *Graph_Graph_from_hBPurityMC42 = new TH1F("Graph_Graph_from_hBPurityMC42","hBPurityMC",100,80.364,174.876);
   Graph_Graph_from_hBPurityMC42->SetMinimum(0.2425548);
   Graph_Graph_from_hBPurityMC42->SetMaximum(0.3689491);
   Graph_Graph_from_hBPurityMC42->SetDirectory(0);
   Graph_Graph_from_hBPurityMC42->SetStats(0);
   Graph_Graph_from_hBPurityMC42->SetLineStyle(0);
   Graph_Graph_from_hBPurityMC42->SetLineWidth(2);
   Graph_Graph_from_hBPurityMC42->SetMarkerStyle(20);
   Graph_Graph_from_hBPurityMC42->GetXaxis()->SetLabelFont(42);
   Graph_Graph_from_hBPurityMC42->GetXaxis()->SetLabelOffset(0.007);
   Graph_Graph_from_hBPurityMC42->GetXaxis()->SetLabelSize(0.05);
   Graph_Graph_from_hBPurityMC42->GetXaxis()->SetTitleSize(0.05);
   Graph_Graph_from_hBPurityMC42->GetXaxis()->SetTitleOffset(1.1);
   Graph_Graph_from_hBPurityMC42->GetXaxis()->SetTitleFont(42);
   Graph_Graph_from_hBPurityMC42->GetYaxis()->SetNdivisions(408);
   Graph_Graph_from_hBPurityMC42->GetYaxis()->SetLabelFont(42);
   Graph_Graph_from_hBPurityMC42->GetYaxis()->SetLabelOffset(0.007);
   Graph_Graph_from_hBPurityMC42->GetYaxis()->SetLabelSize(0.05);
   Graph_Graph_from_hBPurityMC42->GetYaxis()->SetTitleSize(0.05);
   Graph_Graph_from_hBPurityMC42->GetYaxis()->SetTitleOffset(1.3);
   Graph_Graph_from_hBPurityMC42->GetYaxis()->SetTitleFont(42);
   Graph_Graph_from_hBPurityMC42->GetZaxis()->SetLabelFont(42);
   Graph_Graph_from_hBPurityMC42->GetZaxis()->SetLabelOffset(0.007);
   Graph_Graph_from_hBPurityMC42->GetZaxis()->SetLabelSize(0.05);
   Graph_Graph_from_hBPurityMC42->GetZaxis()->SetTitleSize(0.06);
   Graph_Graph_from_hBPurityMC42->GetZaxis()->SetTitleFont(42);
   grae->SetHistogram(Graph_Graph_from_hBPurityMC42);
   
   grae->Draw("p,");
   
   TLegend *leg = new TLegend(0.25,0.6,0.8,0.8,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(43);
   leg->SetTextSize(23);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(19);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("NULL","PbPb, #int L dt = 150 #mub^{-1}","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   //entry->SetTextFont(42);
   entry=leg->AddEntry("Graph_from_hBPurityMC","PYTHIA+HYDJET 1.8","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(2);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.2);
   //entry->SetTextFont(42);
   entry=leg->AddEntry("Graph_from_hBPurityData","Template fit to data","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(25);
   entry->SetMarkerSize(1.5);
   //entry->SetTextFont(42);
   leg->Draw();
   TLatex *   tex = new TLatex(90,0.05,"Centrality 0-100%");
   tex->SetTextFont(43);
   tex->SetTextSize(22);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(81,1.02,"CMS Preliminary");
   tex->SetTextFont(43);
   tex->SetTextSize(22);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(160,1.02,"#sqrt{s_{NN}} = 2.76 TeV");
   tex->SetTextFont(43);
   tex->SetTextSize(22);
   tex->SetLineWidth(2);
   tex->Draw();
   cBPurity->Modified();
   cBPurity->cd();
   cBPurity->SetSelected(cBPurity);
}
