mkdir systematics
root -l -b -q "analyzeJetTrees.C+(\"$1\",\"systematics/data-smeared-1.root\",0,0,0,0,0,1)"
root -l -b -q "analyzeJetTrees.C+(\"$1\",\"systematics/data-smeared-2.root\",0,0,0,0,0,1)"
root -l -b -q "analyzeJetTrees.C+(\"$1\",\"systematics/data-smeared-3.root\",0,0,0,0,0,1)"
root -l -b -q "analyzeJetTrees.C+(\"$1\",\"systematics/data-smeared-4.root\",0,0,0,0,0,1)"
root -l -b -q "analyzeJetTrees.C+(\"$1\",\"systematics/data-smeared-5.root\",0,0,0,0,0,1)"
root -l -b -q "analyzeJetTrees.C+(\"$1\",\"systematics/data-smeared-6.root\",0,0,0,0,0,1)"
root -l -b -q "analyzeJetTrees.C+(\"$1\",\"systematics/data-smeared-7.root\",0,0,0,0,0,1)"
root -l -b -q "analyzeJetTrees.C+(\"$1\",\"systematics/data-smeared-8.root\",0,0,0,0,0,1)"
root -l -b -q "analyzeJetTrees.C+(\"$1\",\"systematics/data-smeared-9.root\",0,0,0,0,0,1)"
root -l -b -q "analyzeJetTrees.C+(\"$1\",\"systematics/data-smeared-10.root\",0,0,0,0,0,1)"
root -l -b -q "analyzeJetTrees.C+(\"$1\",\"systematics/data-smeared-11.root\",0,0,0,0,0,1)"
root -l -b -q "analyzeJetTrees.C+(\"$1\",\"systematics/data-smeared-12.root\",0,0,0,0,0,1)"
root -l -b -q "analyzeJetTrees.C+(\"$1\",\"systematics/data-smeared-13.root\",0,0,0,0,0,1)"
root -l -b -q "analyzeJetTrees.C+(\"$1\",\"systematics/data-smeared-14.root\",0,0,0,0,0,1)"
root -l -b -q "analyzeJetTrees.C+(\"$1\",\"systematics/data-smeared-15.root\",0,0,0,0,0,1)"
root -l -b -q "analyzeJetTrees.C+(\"$1\",\"systematics/data-smeared-16.root\",0,0,0,0,0,1)"
root -l -b -q "analyzeJetTrees.C+(\"$1\",\"systematics/data-smeared-17.root\",0,0,0,0,0,1)"
root -l -b -q "analyzeJetTrees.C+(\"$1\",\"systematics/data-smeared-18.root\",0,0,0,0,0,1)"
root -l -b -q "analyzeJetTrees.C+(\"$1\",\"systematics/data-smeared-19.root\",0,0,0,0,0,1)"
root -l -b -q "analyzeJetTrees.C+(\"$1\",\"systematics/data-smeared-20.root\",0,0,0,0,0,1)"
rm data-smeared.root
hadd data-smeared.root systematics/data-smeared-*.root

root -l -b -q "analyzeJetTrees.C+(\"$1\",\"systematics/data-Ineff-1.root\",0,0,0,0,0,0,1)"
root -l -b -q "analyzeJetTrees.C+(\"$1\",\"systematics/data-Ineff-2.root\",0,0,0,0,0,0,1)"
root -l -b -q "analyzeJetTrees.C+(\"$1\",\"systematics/data-Ineff-3.root\",0,0,0,0,0,0,1)"
root -l -b -q "analyzeJetTrees.C+(\"$1\",\"systematics/data-Ineff-4.root\",0,0,0,0,0,0,1)"
root -l -b -q "analyzeJetTrees.C+(\"$1\",\"systematics/data-Ineff-5.root\",0,0,0,0,0,0,1)"
root -l -b -q "analyzeJetTrees.C+(\"$1\",\"systematics/data-Ineff-6.root\",0,0,0,0,0,0,1)"
root -l -b -q "analyzeJetTrees.C+(\"$1\",\"systematics/data-Ineff-7.root\",0,0,0,0,0,0,1)"
root -l -b -q "analyzeJetTrees.C+(\"$1\",\"systematics/data-Ineff-8.root\",0,0,0,0,0,0,1)"
root -l -b -q "analyzeJetTrees.C+(\"$1\",\"systematics/data-Ineff-9.root\",0,0,0,0,0,0,1)"
root -l -b -q "analyzeJetTrees.C+(\"$1\",\"systematics/data-Ineff-10.root\",0,0,0,0,0,0,1)"
root -l -b -q "analyzeJetTrees.C+(\"$1\",\"systematics/data-Ineff-11.root\",0,0,0,0,0,0,1)"
root -l -b -q "analyzeJetTrees.C+(\"$1\",\"systematics/data-Ineff-12.root\",0,0,0,0,0,0,1)"
root -l -b -q "analyzeJetTrees.C+(\"$1\",\"systematics/data-Ineff-13.root\",0,0,0,0,0,0,1)"
root -l -b -q "analyzeJetTrees.C+(\"$1\",\"systematics/data-Ineff-14.root\",0,0,0,0,0,0,1)"
root -l -b -q "analyzeJetTrees.C+(\"$1\",\"systematics/data-Ineff-15.root\",0,0,0,0,0,0,1)"
root -l -b -q "analyzeJetTrees.C+(\"$1\",\"systematics/data-Ineff-16.root\",0,0,0,0,0,0,1)"
root -l -b -q "analyzeJetTrees.C+(\"$1\",\"systematics/data-Ineff-17.root\",0,0,0,0,0,0,1)"
root -l -b -q "analyzeJetTrees.C+(\"$1\",\"systematics/data-Ineff-18.root\",0,0,0,0,0,0,1)"
root -l -b -q "analyzeJetTrees.C+(\"$1\",\"systematics/data-Ineff-19.root\",0,0,0,0,0,0,1)"
root -l -b -q "analyzeJetTrees.C+(\"$1\",\"systematics/data-Ineff-20.root\",0,0,0,0,0,0,1)"

root -l -b -q "analyzeJetTrees.C+(\"$1\",\"data-2ndJetCorrected.root\",0,0,0,0,1,0,0)"

rm data-Ineff.root
hadd data-Ineff.root systematics/data-Ineff-*.root
